services:
  mgmt-db:
    image: postgres:15
    environment:
      POSTGRES_DB: mgnt-db
      POSTGRES_PASSWORD: admin123  # 保持密码一致
    ports:
      - "5432:5432"

  ai-backend:
    build: .
    environment:
      DATABASE_URL: "postgresql://postgres:admin123@mgmt-db:5432/mgnt-db"
      IN_DOCKER: "true"  # 新增环境变量标识
    depends_on:
      mgmt-db:
        condition: service_healthy
