services:
  mgnt-db:
    image: postgres:13
    environment:
      POSTGRES_DB: mgnt-db
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  ai-backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      mgnt-db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://postgres:mysecretpassword@mgnt-db:5432/mgnt-db"
