services:
  mgmt-db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: mgnt-db
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data  # 新增数据持久化卷      
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
