services:
  mgmt-db:
    image: postgres:15
    environment:
      POSTGRES_DB: mgnt-db
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
